name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
      - name: Set up golangci-lint
        run: sudo snap install golangci-lint --classic
      - name: Set up bluez
        run: sudo apt-get install bluetooth
      - name: Install
        run: make install
      - name: Test
        run: make test
      # Disable coverage reports because BlueZ is not available in the GitHub Actions virtual environment.
      # - name: Upload coverage reports to Codecov
      #  uses: codecov/codecov-action@v4
      #  with:
      #    token: ${{ secrets.CODECOV_TOKEN }}
      #    files: ble-cover.out
